services:
  # --- Backend API (FastAPI) ---
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    # ports removed (exposed internally only)
    restart: on-failure
    volumes:
      - ./backend:/app
      # This will be the main storage for original photos and thumbnails
      - storage_data:/srv/photo-timeline/storage
    environment:
      - DATABASE_URL=postgresql://user:password@postgres/phototimeline
      - REDIS_URL=redis://redis:6379
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - AUTO_CREATE_TABLES=true
      # Email configuration
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      - MAIL_USER=${MAIL_USER:-}
      - MAIL_PASSWORD=${MAIL_PASSWORD:-}
      - MAIL_FROM=${MAIL_FROM:-}
      - MAIL_FROM_NAME=Photo Timeline
      - MAIL_SECURE=true
      - FRONTEND_URL=https://timeline.ysw.kr
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 5s
      timeout: 5s
      retries: 6
      start_period: 20s

  # --- Frontend (Next.js) ---
  frontend:
    build:
      context: ./frontend
    # ports removed (handled by nginx proxy)
    restart: on-failure
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      backend:
        condition: service_healthy

  # --- Background Worker (RQ) ---
  worker:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: ["python", "-u", "worker.py"]
    restart: on-failure
    volumes:
      - ./backend:/app
      - storage_data:/srv/photo-timeline/storage
    environment:
      - DATABASE_URL=postgresql://user:password@postgres/phototimeline
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      backend:
        condition: service_healthy

  # --- Database (PostgreSQL + PostGIS) ---
  postgres:
    image: postgis/postgis:16-3.4
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=phototimeline
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d phototimeline"]
      interval: 2s
      timeout: 3s
      retries: 10
      start_period: 10s

  # --- Cache (Redis) ---
  redis:
    image: redis:7-alpine

  # --- Web Server (Nginx) ---
  nginx:
    image: nginx:1.25-alpine
    restart: on-failure
    ports:
      - "3067:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      frontend:
        condition: service_started
      backend:
        condition: service_healthy

volumes:
  postgres_data:
  storage_data:
