name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgis/postgis:16-3.4
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: phototimeline_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y exiftool

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e ./libs/photo_core
          pip install -r backend/requirements.txt

      - name: Run photo_core tests
        run: |
          pytest tests/test_exif.py tests/test_cluster.py -v

      - name: Run database model tests
        run: |
          pytest tests/test_models_basic.py -v

      - name: Run storage tests
        run: |
          pytest tests/test_storage.py -v

      - name: Test FastAPI app import
        run: |
          cd backend && python -c "from main import app; print('✅ FastAPI app imports successfully')"
